services:
  weather-app-db-postgres:
    image: postgres:16.1-alpine
    container_name: weather-app-postgres
    restart: no
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/weather-app/data

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
