import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/providers/store/StoreProvider";
import Navbar from "@/components/Navbar/Navbar";
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: "Weather Application",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <StoreProvider>
        <body className="bg-cover bg-gradient-to-r from-blue-500 to-blue-300">
          <Navbar />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
